sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull fldc/artful
  - docker run fldc/artful /bin/sh "apt-get install libhdf5-dev libboost-all-dev libgsl-dev libarmadillo-dev

compiler:
  - clang
  - gcc

script:
  - cmake  .
  - make -j 4
  - make test
  - curl -s https://codecov.io/bash | bash -