sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t joeydumont/bionic .
  - docker run -itd --name build joeydumont/bionic
  - docker exec build apt-get install -y --force-yes libhdf5-dev libboost-dev libgsl-dev libarmadillo-dev

compiler:
  - gcc

script:
  - docker exec build cmake .
  - docker exec build make -j 4
  - docker exec build make test
  - docker exec build curl -s https://codecov.io/bash | bash -

git:
  submodules: false