sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t joeydumont/bionic .
  - docker run -itd --name build joeydumont/bionic
  - docker exec build apt-get install -y --force-yes libhdf5-dev libboost-dev libgsl-dev libarmadillo-dev
  - docker exec build git clone https://github.com/joeydumont/mellotron.git joeydumont/mellotron
  - docker exec build cd joeydumont/mellotron
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker exec build git fetch origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge:; bundle exec build git checkout -qF FETCH_HEAD; fi'

compiler:
  - gcc
  - clang

script:
  - docker exec build cmake .
  - docker exec build make -j 4
  - docker exec build make test
  - docker exec build curl -s https://codecov.io/bash | bash -

git:
  submodules: false